dist: trusty
language: node_js
node_js: 12.18.4

addons:
  sonarcloud:
    organization: "mecassauro"
    token: ${SONAR_TOKEN}

cache:
  directories:
    - node_modules

stages:
  - Install
  - Test
  - Quality gate

jobs:
  include:
    - stage: Install
      script:
        - yarn install
    - stage: Test
      script:
        - yarn run test --passWithNoTests --watchAll=false --coverage
    - stage: Quality gate
      script:
        - sonar-scanner